import requests
import json

# 1. The Query (Ask for all bus stops in Sri Lanka)
# We use a Bounding Box for Sri Lanka: (South, West, North, East)
overpass_url = "http://overpass-api.de/api/interpreter"
overpass_query = """
[out:json][timeout:60];
(
  node["highway"="bus_stop"](5.9,79.5,9.9,81.9);
  node["public_transport"="platform"](5.9,79.5,9.9,81.9);
);
out body;
"""

print("🚀 Connecting to OpenStreetMap... (This might take 10-20 seconds)")

try:
    response = requests.get(overpass_url, params={'data': overpass_query})
    data = response.json()
    
    stops_found = 0
    formatted_lines = []
    
    # 2. Process the Data
    print(f"✅ Downloaded raw data. Processing {len(data['elements'])} elements...")

    for element in data['elements']:
        tags = element.get('tags', {})
        lat = element.get('lat')
        lon = element.get('lon')
        
        # Get the name. Priority: English Name -> Local Name
        name = tags.get('name:en')
        if not name:
            name = tags.get('name')
            
        # Clean up the name
        if name:
            # Remove double quotes to prevent syntax errors
            clean_name = name.replace('"', '').strip()
            
            # Formatting line: "Name": [Lat, Lng],
            # We use 5 decimal places for precision
            line = f'    "{clean_name}": [{lat:.5f}, {lon:.5f}],'
            formatted_lines.append(line)
            stops_found += 1

    # 3. Save to File
    output_filename = "stop_data.js"
    
    with open(output_filename, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED BUS STOPS\n")
        f.write("const autoGeneratedStops = {\n")
        
        # Write all unique lines (using set to remove duplicates)
        unique_lines = sorted(list(set(formatted_lines)))
        
        for line in unique_lines:
            f.write(line + "\n")
            
        f.write("};\n")

    print(f"🎉 Success! Extracted {len(unique_lines)} unique bus stops.")
    print(f"📂 Saved to file: {output_filename}")
    print("👉 Now copy the content of 'stop_data.js' into your buses.js file.")

except Exception as e:
    print("❌ Error:", e)